{{- if and (not .Values.secrets.existingSecret) .Values.secrets.auditApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "orchid-ranker.fullname" . }}-secrets
type: Opaque
stringData:
  auditApiKey: {{ .Values.secrets.auditApiKey | quote }}
{{- end }}
