apiVersion: v1
kind: Service
metadata:
  name: {{ include "orchid-ranker.fullname" . }}
  labels:
    {{- include "orchid-ranker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
  selector:
    {{- include "orchid-ranker.selectorLabels" . | nindent 4 }}
